server:
    port: ${APP_PORT}
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: user-vaccination-inventory
    datasource:
        password: ${DS_PASSWORD}
        testWhileIdle: true
        url: ${DS_URL}
        username: ${DS_USERNAME}
        validationQuery: SELECT 1
    devtools:
        restart:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: ${DB_DDL_AUTO}
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            use-new-id-generator-mappings: true
        properties:
            hibernate:
                show_sql: ${SHOW_SQL}
keycloak:
    auth-server-url: ${SSO_URL_BASE}${AUTH_SERVER_URL}
    realm: ${SSO_REALM}
    ssl-required: external
    resource: user-vaccination-inventory
    public-client: true
    cors: true
    use-resource-role-mappings: true
    bearer-only: true
sso:
  client_id: ${SSO_CLIENT_ID}
  grant_type: ${SSO_GRANT_TYPE}
  username: ${SSO_USERNAME}
  password: ${SSO_PASSWORD}
  url:
      user:
          registration: ${SSO_URL_USER_REGISTRATION} 
      token: ${SSO_URL_TOKEN}
      realms: ${SSO_URL_REALMS}
      realm: ${SSO_REALM}  